"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowRight, CalendarCheck2, Check, ChevronRight, CircleAlert, Clock3, Moon, Sun, Users } from "lucide-react";
import { useApp } from "./provider";
import { PageTitle, Panel, Avatar } from "./common";
import { Button } from "./ui/button";
import { coverage, dateLabel, filledDays, isOpen, isValidated, monthDays, monthLabel, type Shift } from "@/lib/domain";
export function Dashboard() {
  const { state, campaignId } = useApp();
  const [mode, setMode] = useState<"potential" | "planned">("potential");
  const campaign = state.campaigns.find(c => c.id === campaignId)!;
  const days = monthDays(campaign.month);
  const respondents = state.agents.filter(a => isValidated(state, campaignId, a.id));
  const pending = state.agents.filter(a => !isValidated(state, campaignId, a.id));
  const data = days.flatMap(date => (["DAY", "NIGHT"] as Shift[]).map(shift => ({ date, shift, ...coverage(state, campaignId, date, shift, mode) })));
  const dayDeficits = data.filter(c => c.shift === "DAY" && !c.covered).length;
  const nightDeficits = data.filter(c => c.shift === "NIGHT" && !c.covered).length;
  const covered = data.filter(c => c.covered).length;
  const percent = Math.round(respondents.length / state.agents.length * 100);
  return <><PageTitle eyebrow="VUE D’ENSEMBLE" title="Une équipe prête, ensemble." description={`Pilotez les disponibilités et la couverture de ${monthLabel(campaign.month)}.`} action={<Button asChild><Link href="/planning"><CalendarCheck2 size={17} />Construire le planning<ArrowRight size={17} /></Link></Button>} />
    <div className="campaign-ribbon"><div className="ribbon-icon"><CalendarCheck2 size={22} /></div><div><strong>{campaign.name}</strong><span>{isOpen(campaign) ? "La campagne est ouverte" : "La campagne est fermée"} · Réponses jusqu’au {dateLabel(campaign.closesOn)}</span></div><span className={`pill ${isOpen(campaign) ? "pill-green" : "pill-gray"}`}><span className="live-dot" />{isOpen(campaign) ? "En cours" : "Clôturée"}</span><Link href="/campagnes">Gérer la campagne<ChevronRight size={17} /></Link></div>
    <div className="section-toolbar"><div className="segmented" aria-label="Mesure de couverture"><button aria-pressed={mode === "potential"} className={mode === "potential" ? "selected" : ""} onClick={() => setMode("potential")}>Couverture potentielle</button><button aria-pressed={mode === "planned"} className={mode === "planned" ? "selected" : ""} onClick={() => setMode("planned")}>Couverture planifiée</button></div><span className="muted small">{mode === "potential" ? "Disponibilités validées" : "Affectations du brouillon"} · effectifs et qualifications</span></div>
    <div className="stats-grid"><div className="stat-card"><div className="stat-label">Réponses validées<span className="stat-icon blue"><Users size={19} /></span></div><div className="stat-number">{respondents.length}<span>/ {state.agents.length}</span><span className="stat-badge">{percent} %</span></div><div className="mini-progress"><i style={{ width: `${percent}%` }} /></div><p><span className="text-blue">{pending.length} réponses</span> restent à valider</p></div><div className="stat-card"><div className="stat-label">Journées en déficit<span className="stat-icon orange"><Sun size={20} /></span></div><div className="stat-number">{dayDeficits}<span>journées</span></div><p><span className="dot orange" />{mode === "potential" ? "Disponibilités à compléter" : "Affectations à compléter"}</p></div><div className="stat-card"><div className="stat-label">Nuits en déficit<span className="stat-icon purple"><Moon size={19} /></span></div><div className="stat-number">{nightDeficits}<span>nuits</span></div><p><span className="dot purple" />{mode === "potential" ? "Disponibilités à compléter" : "Affectations à compléter"}</p></div><div className="stat-card"><div className="stat-label">Créneaux couverts<span className="stat-icon green"><Check size={20} /></span></div><div className="stat-number">{covered}<span>/ {days.length * 2}</span></div><p><span className="dot green" />{Math.round(covered / data.length * 100)} % de couverture {mode === "potential" ? "potentielle" : "planifiée"}</p></div></div>
    <Panel title="La couverture, jour après jour" subtitle={`${monthLabel(campaign.month)} · ${mode === "potential" ? "Potentielle — réponses validées" : "Planifiée — brouillon"}`} action={<div className="coverage-legend"><span><i className="covered" />Couvert</span><span><i className="deficit" />Déficit</span></div>}><div className="heatmap-scroll"><div className="heatmap"><div className="heatmap-label" />{days.map(date => <div key={date} className={`heatmap-date ${[0, 6].includes(new Date(`${date}T12:00`).getDay()) ? "weekend" : ""}`}><small>{dateLabel(date, { weekday: "short" }).slice(0, 1)}</small><b>{Number(date.slice(-2))}</b></div>)}{(["DAY", "NIGHT"] as Shift[]).map(shift => <div className="heatmap-row" key={shift}><div className="heatmap-label">{shift === "DAY" ? <Sun size={15} /> : <Moon size={15} />}{shift === "DAY" ? "Jour" : "Nuit"}</div>{days.map(date => { const c = coverage(state, campaignId, date, shift, mode); return <Link key={date} className={`heatmap-cell ${c.covered ? "covered" : "deficit"}`} href={`/planning?date=${date}&shift=${shift}`} aria-label={`${dateLabel(date)} ${shift === "DAY" ? "jour" : "nuit"} : ${c.actual} sur ${c.need}, ${c.covered ? "couvert" : "déficit"}`} title={`${c.actual}/${c.need} agents · ${c.covered ? "Qualifications couvertes" : "Besoins non couverts"}`}>{c.actual}<small>/{c.need}</small></Link>; })}</div>)}</div></div><div className="panel-footnote"><CircleAlert size={14} />Un créneau est couvert lorsque les effectifs et les qualifications sont réunis.<Link href="/disponibilites">Voir les disponibilités<ArrowRight size={14} /></Link></div></Panel>
    <div className="dashboard-bottom"><Panel title="La mobilisation de votre équipe" subtitle="Seules les réponses explicitement validées sont comptabilisées." action={<span className="pill pill-blue">{state.agents.length} agents</span>}><div className="response-overview"><div className="donut" style={{ background: `conic-gradient(var(--blue) ${percent}%, #edf1f7 0)` }}><div><strong>{percent}<small>%</small></strong><span>ont validé</span></div></div><div className="response-counts"><div><span><i className="dot blue" />Réponses validées</span><strong>{respondents.length}</strong></div><div><span><i className="dot gray" />En attente de validation</span><strong>{pending.length}</strong></div><Link href="/disponibilites">Consulter la synthèse<ArrowRight size={15} /></Link></div></div><div className="pending-list">{pending.slice(0, 3).map(a => <div key={a.id}><Avatar agent={a} /><span><strong>{a.name}</strong><small>{a.team}</small></span><span className="pending-progress">{filledDays(state, campaign, a.id)}/{days.length} jours saisis</span><Clock3 size={15} /></div>)}</div></Panel><Panel title="Votre prochaine étape" subtitle="De la disponibilité au planning publié."><div className="next-step"><span className="step-number">01</span><div><h3>Compléter les affectations</h3><p>Comparez les agents disponibles aux besoins de chaque garde.</p><Button variant="secondary" asChild><Link href="/planning">Ouvrir le planning<ArrowRight size={16} /></Link></Button></div></div><div className="next-step"><span className="step-number muted-step">02</span><div><h3>Publier les créneaux couverts</h3><p>Les agents retrouvent uniquement les gardes publiées dans leur planning.</p></div></div><div className="small-note"><ShieldIcon />Une disponibilité est une possibilité.<br />Une affectation est un engagement au planning.</div></Panel></div>
  </>;
}
function ShieldIcon() { return <CalendarCheck2 size={20} />; }
